#!/usr/bin/env python3

import os
import sys

import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    
    #ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # sets screen name
    screen_name = sys.argv[1].strip("@")
    
    # gets 50 most recent tweets
    tweets = helpers.get_user_timeline(screen_name, 50)
    
    # checks if username is invalid, and throws an error
    if tweets == None:
        sys.exit("Invalid username.")
        
    # if it is valid, analyze the tweets
    for tweet in tweets:
        score = analyze.analyzer(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))
            
main()            